stages:
  - build
  - test
  - deploy

build_docker_image:
  stage: build
  script:
    - make build_server

execute_tests:
  stage: test
  script:
    - make test_server

code_quality:
  stage: test
  script:
    - make quality_server
