%YAML 1.2
---

Parameters:
   module: 'numbers'
   class: 'Number'
   list:
   - config1:
     weight: 0.2
     module: 'numbers'
     class: 'Number'
   - config2:
     weight: 0.1
     module: 'numbers'
     class: 'Number'